name: Create release

on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  GH_TOKEN: ${{ github.GH_TOKEN }}

jobs:
  create_release:
    name: Create Release
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Get release version
        id: release-version
        run: |
          export VERSION=$(node --eval="process.stdout.write(require('./package.json').version)")
          echo "::set-output name=version::$VERSION"

      - name: Install dependencies
        run: |
          npm install

      - name: Build for MacOS ARM
        run: |
          npm run electron:build:mac-arm

      - name: Build for MacOS x64
        run: |
          npm run electron:build:mac64

      - name: Build for Windows x64
        run: |
          npm run electron:build:win64

      - name: Create release
        uses: actions/create-release@v1
        id: create-release
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ steps.release-version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.GH_TOKEN }}

      - name: Upload MacOS ARM artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: ./dist_electron/WatchDog-${{ steps.release-version.outputs.version }}-arm64.dmg
          asset_name: WatchDog-${{ steps.release-version.outputs.version }}-arm.dmg
          asset_content_type: application/octet-stream

      - name: Upload MacOS x64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist_electron/WatchDog-${{ steps.release-version.outputs.version }}.dmg
          asset_name: WatchDog-${{ steps.release-version.outputs.version }}-64.dmg
          asset_content_type: application/octet-stream

      - name: Upload Windows x64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist_electron/WatchDog Setup ${{ steps.release-version.outputs.version }}.exe
          asset_name: WatchDog ${{ steps.release-version.outputs.version }}.exe
          asset_content_type: application/vnd.microsoft.portable-executable